export const PORTFOLIO_CATEGORIES = [
  { id: 'all', label: 'Show all' },
  { id: 'villas', label: 'Villas' },
  { id: 'office', label: 'Office' },
  { id: 'interior', label: 'Interior' },
  { id: 'commercial', label: 'Commercial' },
];

export const PORTFOLIO_PROJECTS = [
  {
    id: 1,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/smitha-home.jpg',
      '/images/anil-home.jpg',
      '/images/bijesh-home.jpg',
      '/images/int1.jpg',
    ],
  },
  {
    id: 2,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/anil-home.jpg',
      '/images/home-slider1.jpg',
      '/images/bijesh-home.jpg',
      '/images/arche.jpg',
    ],
  },
  {
    id: 3,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/bijesh-home.jpg',
      '/images/construct.jpg',
      '/images/anil-home.jpg',
      '/images/home-slider2.jpg',
    ],
  },
  {
    id: 4,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'interior',
    categoryBadge: 'Interior',
    location: 'Chavara, Kollam',
    images: [
      '/images/int2.jpg',
      '/images/interior.jpg',
      '/images/int5.jpg',
      '/images/smitha-home.jpg',
    ],
  },
  {
    id: 5,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/smitha-home.jpg',
      '/images/int3.jpg',
      '/images/int4.jpg',
      '/images/anil-home.jpg',
    ],
  },
  {
    id: 6,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/anil-home.jpg',
      '/images/home-slider1.jpg',
      '/images/bijesh-home.jpg',
    ],
  },
  {
    id: 7,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/bijesh-home.jpg',
      '/images/anil-home.jpg',
      '/images/construct.jpg',
    ],
  },
  {
    id: 8,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'interior',
    categoryBadge: 'Interior',
    location: 'Chavara, Kollam',
    images: [
      '/images/int2.jpg',
      '/images/int1.jpg',
      '/images/interior.jpg',
    ],
  },
  {
    id: 9,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'commercial',
    categoryBadge: 'Commercial',
    location: 'Chavara, Kollam',
    images: [
      '/images/construct.jpg',
      '/images/arche.jpg',
      '/images/struct.jpg',
    ],
  },
  {
    id: 10,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/home-slider1.jpg',
      '/images/anil-home.jpg',
      '/images/smitha-home.jpg',
    ],
  },
  {
    id: 11,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'interior',
    categoryBadge: 'Interior',
    location: 'Chavara, Kollam',
    images: [
      '/images/int5.jpg',
      '/images/int2.jpg',
      '/images/int3.jpg',
    ],
  },
  {
    id: 12,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/bijesh-home.jpg',
      '/images/about.jpg',
      '/images/anil-home.jpg',
    ],
  },
  {
    id: 13,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/smitha-home.jpg',
      '/images/int1.jpg',
      '/images/int4.jpg',
    ],
  },
  {
    id: 14,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/anil-home.jpg',
      '/images/bijesh-home.jpg',
      '/images/home-slider1.jpg',
    ],
  },
  {
    id: 15,
    title: 'DR. SREECHITH - CHAVARA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Chavara, Kollam',
    images: [
      '/images/bijesh-home.jpg',
      '/images/construct.jpg',
      '/images/smitha-home.jpg',
    ],
  },
  {
    id: 16,
    title: 'VERTEX TECH PARK - INFOPARK',
    category: 'office',
    categoryBadge: 'Office',
    location: 'Infopark, Kochi',
    images: [
      '/images/work-area.jpg',
      '/images/arche.jpg',
      '/images/construct.jpg',
    ],
  },
  {
    id: 17,
    title: 'NEXUS CO-WORKING HUB',
    category: 'office',
    categoryBadge: 'Office',
    location: 'Calicut',
    images: [
      '/images/work-area.jpg',
      '/images/about.jpg',
      '/images/int4.jpg',
    ],
  },
  {
    id: 18,
    title: 'HORIZON COMMERCIAL TOWERS',
    category: 'commercial',
    categoryBadge: 'Commercial',
    location: 'MG Road, Kochi',
    images: [
      '/images/arche.jpg',
      '/images/construct.jpg',
      '/images/struct.jpg',
    ],
  },
  {
    id: 19,
    title: 'LUMINA LUXURY RESIDENCE',
    category: 'interior',
    categoryBadge: 'Interior',
    location: 'Vyttila, Kochi',
    images: [
      '/images/int4.jpg',
      '/images/interior.jpg',
      '/images/int2.jpg',
    ],
  },
  {
    id: 20,
    title: 'SERENITY RETREAT VILLA',
    category: 'villas',
    categoryBadge: 'Villas',
    location: 'Kumarakom',
    images: [
      '/images/home-slider2.jpg',
      '/images/anil-home.jpg',
      '/images/bijesh-home.jpg',
    ],
  },
  {
    id: 21,
    title: 'APEX CORPORATE HEADQUARTERS',
    category: 'office',
    categoryBadge: 'Office',
    location: 'Trivandrum',
    images: [
      '/images/work-area.jpg',
      '/images/struct.jpg',
      '/images/construct.jpg',
    ],
  },
];
