export const ALL_PRODUCTS = [
  {
    id: 1,
    title: 'BULL-WOOD ART LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/int4.jpg',
    rating: 4.9,
  },
  {
    id: 2,
    title: 'LION-WOOD WALL ART LIGHT',
    price: 1800,
    originalPrice: 2800,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int1.jpg',
    rating: 4.8,
  },
  {
    id: 3,
    title: 'PARAMETRIC WOOD LIGHT',
    price: 2200,
    originalPrice: 3200,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int3.jpg',
    rating: 5.0,
  },
  {
    id: 4,
    title: 'WALL HANGING WOOD LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int5.jpg',
    rating: 4.7,
  },
  {
    id: 5,
    title: 'BULL-WOOD ART LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/int5.jpg',
    rating: 4.9,
  },
  {
    id: 6,
    title: 'LION-WOOD WALL ART LIGHT',
    price: 1800,
    originalPrice: 2800,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int3.jpg',
    rating: 4.8,
  },
  {
    id: 7,
    title: 'PARAMETRIC WOOD LIGHT',
    price: 2200,
    originalPrice: 3200,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int1.jpg',
    rating: 5.0,
  },
  {
    id: 8,
    title: 'WALL HANGING WOOD LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int4.jpg',
    rating: 4.7,
  },
  {
    id: 9,
    title: 'BULL-WOOD ART LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/int4.jpg',
    rating: 4.9,
  },
  {
    id: 10,
    title: 'LION-WOOD WALL ART LIGHT',
    price: 1800,
    originalPrice: 2800,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int1.jpg',
    rating: 4.8,
  },
  {
    id: 11,
    title: 'PARAMETRIC WOOD LIGHT',
    price: 2200,
    originalPrice: 3200,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int3.jpg',
    rating: 5.0,
  },
  {
    id: 12,
    title: 'WALL HANGING WOOD LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int5.jpg',
    rating: 4.7,
  },
  {
    id: 13,
    title: 'BULL-WOOD ART LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/int5.jpg',
    rating: 4.9,
  },
  {
    id: 14,
    title: 'LION-WOOD WALL ART LIGHT',
    price: 1800,
    originalPrice: 2800,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int3.jpg',
    rating: 4.8,
  },
  {
    id: 15,
    title: 'PARAMETRIC WOOD LIGHT',
    price: 2200,
    originalPrice: 3200,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int1.jpg',
    rating: 5.0,
  },
  {
    id: 16,
    title: 'WALL HANGING WOOD LIGHT',
    price: 1500,
    originalPrice: 2500,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int4.jpg',
    rating: 4.7,
  },
  // Batch 2 (revealed upon clicking "Show More")
  {
    id: 17,
    title: 'ARCIO HANGING WOOD LIGHT',
    price: 1950,
    originalPrice: 2900,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int2.jpg',
    rating: 4.9,
  },
  {
    id: 18,
    title: 'GEOMETRIC SLAT WOOD FIXTURE',
    price: 1650,
    originalPrice: 2400,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int5.jpg',
    rating: 4.8,
  },
  {
    id: 19,
    title: 'CONTEMPORARY CURVE PENDANT',
    price: 2400,
    originalPrice: 3500,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/arche.jpg',
    rating: 5.0,
  },
  {
    id: 20,
    title: 'WARM AMBIENT ACCENT LIGHT',
    price: 1350,
    originalPrice: 2100,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/interior.jpg',
    rating: 4.6,
  },
  {
    id: 21,
    title: 'NORDIC RIBBED PENDANT LIGHT',
    price: 2150,
    originalPrice: 3100,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int1.jpg',
    rating: 4.9,
  },
  {
    id: 22,
    title: 'DIAMOND LATTICE SCONCE',
    price: 1550,
    originalPrice: 2450,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int5.jpg',
    rating: 4.7,
  },
  {
    id: 23,
    title: 'ORGANIC WAVE WOOD CHANDELIER',
    price: 2950,
    originalPrice: 4100,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int3.jpg',
    rating: 5.0,
  },
  {
    id: 24,
    title: 'MINIMALIST TIMBER WALL LIGHT',
    price: 1450,
    originalPrice: 2250,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/l1.jpg',
    rating: 4.8,
  },
  {
    id: 25,
    title: 'BULL-WOOD ART LIGHT - TEAK',
    price: 1600,
    originalPrice: 2600,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/int4.jpg',
    rating: 4.9,
  },
  {
    id: 26,
    title: 'LION-WOOD WALL ART LIGHT - GOLDEN',
    price: 1900,
    originalPrice: 2950,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int1.jpg',
    rating: 4.9,
  },
  {
    id: 27,
    title: 'PARAMETRIC WOOD LIGHT - MAHOGANY',
    price: 2350,
    originalPrice: 3400,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int3.jpg',
    rating: 5.0,
  },
  {
    id: 28,
    title: 'WALL HANGING WOOD LIGHT - OAK',
    price: 1550,
    originalPrice: 2550,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/int5.jpg',
    rating: 4.8,
  },
  {
    id: 29,
    title: 'ARCHITECTURAL LINEAR WOOD LIGHT',
    price: 2600,
    originalPrice: 3700,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/arche.jpg',
    rating: 4.9,
  },
  {
    id: 30,
    title: 'SCULPTURAL BESPOKE ART LIGHT',
    price: 1850,
    originalPrice: 2750,
    category: 'art-light',
    categoryName: 'Art Lights',
    image: '/images/work-area.jpg',
    rating: 4.8,
  },
  {
    id: 31,
    title: 'GEOMETRIC TIMBER SHADE LIGHT',
    price: 1700,
    originalPrice: 2650,
    category: 'pendant-light',
    categoryName: 'Pendant Lights',
    image: '/images/int2.jpg',
    rating: 4.7,
  },
  {
    id: 32,
    title: 'CUSTOM LUXURY WOOD WALL SCONCE',
    price: 1950,
    originalPrice: 2900,
    category: 'wall-light',
    categoryName: 'Wall Lights',
    image: '/images/l2.jpg',
    rating: 5.0,
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Products' },
  { id: 'wall-light', label: 'Wall Lights' },
  { id: 'pendant-light', label: 'Pendant Lights' },
  { id: 'art-light', label: 'Art Lights' },
];

export const SORT_OPTIONS = [
  { id: 'a-z', label: 'A-Z' },
  { id: 'z-a', label: 'Z-A' },
  { id: 'price-low', label: 'Price: Low to High' },
  { id: 'price-high', label: 'Price: High to Low' },
  { id: 'featured', label: 'Featured' },
];
